version: '3'
services:

  poll:
    build: ./poll
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5000:80
    networks:
      - poll-tier

  result:
    build: ./result
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - result-tier
    ports:
      - 5001:80

  worker:
    build: ./worker
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - back-tier
    ports:
      - 5002:80

  redis:
    image: "redis:7.0"
    restart: always
    expose:
      - "6379"
    networks:
      - poll-tier
      - back-tier

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5433:5432"
    networks:
      - result-tier
      - back-tier
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/usr/share/db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
volumes:
  db-data:
    driver: local

networks:
  poll-tier:
    driver: bridge
  result-tier:
    driver: bridge
  back-tier:
    driver: bridge